services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: veh_onboard
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vehicle-onboard-app
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: root
      DB_PASSWORD: 1234
      UPLOAD_DIR: /vehicle-data
    volumes:
      - ./data:/vehicle-data

  nginx:
    image: nginx:latest
    container_name: vehicle_nginx
    ports:
      - "8081:80"
    volumes:
      - ./data:/usr/share/nginx/data:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  mysql_data: